# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit mpitb.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(plotly)
library(ggplot2)
library(palmerpenguins)


## ----library, echo = TRUE-----------------------------------------------------
library(mpitb)

data <- syn_cdta

data <- subset(data, t == 1)

